### ISSUE TITLE
[Feature Request]: make available on desktop

### ISSUE THREAD

**Issue by ceojuice** [ColDog-Studios/ColDog-Locker-Windows#1]
### Contact Details

charlesteller21@gmail.com

### Is your feature request related to a problem?

yes because I have to go and search for the file.

### What is the new feature you want added?

I want coldog locker to be on the desktop so it is easier to access

### Version

v1.0.0

### OS

Windows 10

**Comment by ColDog5044** [comment]
Read the ColDog Locker Update, available here: https://coldogstudios.github.io/news
